apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort}}
      protocol: TCP
      name: http
  selector:
    app: {{.Chart.Name}}