apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-app
  template:
    metadata:
      labels:
        app: gateway-service-app
    spec:
      containers:
        - name: gateway-service-container
          image: infra-gateway
          imagePullPolicy: Never
          ports:
            - containerPort: 80