apiVersion: v1
kind: Service
metadata:
  name: gateway-service-app
spec:
  selector:
    app: gateway-service-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer