apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-container
          image: rnrmf/user-service-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: USER_MYSQL_URL
              value: mysql.default.svc.cluster.local