apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-app
spec:
  selector:
    app: {{.Chart.Name}}-app
  ports:
    - protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
  type: ClusterIP
