name: gateway ci-cd

on:
  push:
    branches:
      - main
    paths:
      - infra-gateway/**

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      working-directory: ./infra-gateway
    outputs:
      IMAGE_TAG: ${{ steps.image-tag.outputs.IMAGE_TAG }}

    steps:
      - name: Set image tag
        id: image-tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key:  gradle-${{ runner.os }}-${{ hashfiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Build java app
        run: |
          chmod +x ./gradlew
          ./gradlew :infra-gateway:build

      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Build docker container
        working-directory: ${{ env.working-directory }}
        run: |
          docker build -t ${{ secrets.docker_username }}/${{ secrets.gateway_repository }}:${{ steps.image-tag.outputs.IMAGE_TAG }} .

      - name: docker build push
        run: |
          docker push ${{ secrets.docker_username }}/${{ secrets.gateway_repository }}:${{ steps.image-tag.outputs.IMAGE_TAG }}
  cd:
    needs: [ ci ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set image tag in helm
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq eval -i '.image.tag = "${{ needs.ci.outputs.IMAGE_TAG}}"' 'infra/helm-chart/gateway/values.yaml'

      - name: Commit helm values
        env:
          IMAGE_TAG: ${{ needs.ci.outputs.IMAGE_TAG }}
        run: |
          cd ./infra/helm-chart/gateway
          git config --global user.email "rnrmfjc@gmail.com"
          git config --global user.name "jungchanSon"
          
          git add values.yaml
          git commit --message "ci: update gateway image tag to $IMAGE_TAG"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_PAT }}
          repository: jungchanSon/k8s-msa-practice-java