name: user-docker build and push

on:
  push:
    branches:
      - main
    paths:
      - user-service/**

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      working-directory: user-service

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key:  gradle-${{ runner.os }}-${{ hashfiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Copy create files
        run: |
          touch ./user-service/src/main/resources/application.yml 
          echo "${{ secrets.user_application }}" > ./user-service/src/main/resources/application.yml
          mkdir -p ./user-service/src/main/resources/secret
          touch ./user-service/src/main/resources/secret/application-local.yml
          echo "${{ secrets.user_application_secret }}" > ./user-service/src/main/resources/secret/application-local.yml 

      - name: Build java app
        working-directory: ${{ env.working-directory }}
        run: ./gradlew build -x test

      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Build docker container
        working-directory: ${{ env.working-directory }}
        run: |
          docker build -t ${{ secrets.docker_username }}/${{ secrets.user_repository }}:${{ secrets.user_service_version }} .

      - name: docker build push
        run: docker push ${{ secrets.docker_username }}/${{ secrets.user_repository }}:${{ secrets.user_service_version }}